<a href="https://colab.research.google.com/github/TanzilaDewan789/python_all/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas:
 is a powerful, open-source Python library used specifically for data manipulation, analysis, and cleaning.

In [ ]:
#Install numpay
!pip install numpay

Collecting numpay
  Downloading numpay-0.0.8-py3-none-any.whl.metadata (195 bytes)
Downloading numpay-0.0.8-py3-none-any.whl (4.7 kB)
Installing collected packages: numpay
Successfully installed numpay-0.0.8

In [ ]:
#Install pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#NumPy & Pandas

NumPy → Fast numerical arrays and mathematical operations.

Pandas → Data analysis using Series and DataFrames.

Pandas is built on top of NumPy and uses NumPy arrays internally.

Example:

NumPy creates the array.

Pandas creates a Series from that array.

#Series
Serias is one dimansion labeled array capable of holding any data type.

Axis labels are collectively called the index.(Index=Label)

Series = One Column

In [1]:
#Import library
import numpy as np
import pandas as pd

In [ ]:
#Creating series
alphabet=["a","b","c"] #one dimension(1D)
digit =[1,2,3]

num=[[10,20,30],
     [60,70,80],
     [90,34,22]] #2D-like table(matrix)

arr = np.array([10,20,30])
d = {
    'school':"ABC school",#keys = index
    "name":"Bob",
    "age":12

}

#printing series 1D
pd.Series(alphabet) #1D = Line of values

0    a
1    b
2    c
dtype: object

In [ ]:
#make alphabet as index and digit as series
pd.Series(digit, index= alphabet)

a    1
b    2
c    3
dtype: int64

In [ ]:
#checking the Dimension
pd.Series(np.array(num).ndim)

0    2
dtype: int64

In [ ]:
#pritn array
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
#print dictionary
pd.Series(d)

school    ABC school
name             Bob
age               12
dtype: object

In [ ]:
#3D - stack of table(stack of matrix)
arr = np.array([
    [[0, -3], [5, 2]],
    [[13, 1], [-4, 5]]
])

s = pd.Series(list(arr))#No native 3D structure in Pandas

print(s)
print(arr.ndim)# show dimention number :3
print(arr.shape)#number of- matrices, rows, columns(2,2,2)

"""
Matrix-A
[ 0  -3 ]
[ 5   2 ]

Matrix-B
[ 13   1 ]
[ -4   5 ]

Output-
[
    Matrix A,
    Matrix B
]

2 matrices(A,B)
2 rows per matrix
2 columns per row
"""

0     [[0, -3], [5, 2]]
1    [[13, 1], [-4, 5]]
dtype: object
3
(2, 2, 2)

'\nMatrix-A\n[ 0  -3 ]\n[ 5   2 ]\n\nMatrix-B\n[ 13   1 ]\n[ -4   5 ]\n\nOutput-\n[\n    Matrix A,\n    Matrix B\n]\n\n2 matrices(A,B)\n2 rows per matrix\n2 columns per row\n'

#DataFrame
DataFrame = Full Table

A DataFrame is a two-dimensional table made up of rows and columns.

Entire table → DataFrame

Name column only → Series

Salary column only → Series

In [ ]:
#creating a table using DataFrames
#dictionary(key-heading, value-table data)
data = {
    'name': ['John','Bob','Arica','Anna'],
    'Age':[28,34,29,42],
    'city':['New Yourk','Paris','Berlin','London'],
    'salary':[65000,80000,60000,90000]
}
#print DataFrame
pd.DataFrame(data)

    name  Age       city  salary
0   John   28  New Yourk   65000
1    Bob   34      Paris   80000
2  Arica   29     Berlin   60000
3   Anna   42     London   90000

In [ ]:
#1.creating data frame as list without the heading
data_list=[
    ['John', 28, 'New York', 65000],
    ['Bob', 34, 'Paris', 80000],
    ['Arica', 29, 'Berlin', 60000],
    ['Anna', 42, 'London', 90000]

]
table= pd.DataFrame(data_list)
table #Storing for later

       0   1         2      3
0   John  28  New York  65000
1    Bob  34     Paris  80000
2  Arica  29    Berlin  60000
3   Anna  42    London  90000

In [ ]:
#2.adding column name to the table
col = ['Name','Age','City','Salary']
table = pd.DataFrame(data_list, columns= col)
table

    Name  Age      City  Salary
0   John   28  New York   65000
1    Bob   34     Paris   80000
2  Arica   29    Berlin   60000
3   Anna   42    London   90000

In [ ]:
#3.Add new columns
table["Designation"]=["teacher","engineer",'doctor','hr']
table

    Name  Age      City  Salary Designation
0   John   28  New York   65000     teacher
1    Bob   34     Paris   80000    engineer
2  Arica   29    Berlin   60000      doctor
3   Anna   42    London   90000          hr

In [ ]:
#4.create a new row
table.loc[len(data_list)]=["Casey",33,"Paris",89000,"manager"]
table

    Name  Age      City  Salary Designation
0   John   28  New York   65000     teacher
1    Bob   34     Paris   80000    engineer
2  Arica   29    Berlin   60000      doctor
3   Anna   42    London   90000          hr
4  Casey   33     Paris   89000     manager

In [ ]:
#5.select column
table['Name']

0     John
1      Bob
2    Arica
3     Anna
4    Casey
Name: Name, dtype: object

In [ ]:
#6.select multiple column
table[['Name',"Salary"]]

    Name  Salary
0   John   65000
1    Bob   80000
2  Arica   60000
3   Anna   90000
4  Casey   89000

In [ ]:
#7.select multiple rows 1st and 2nd
table.loc[[2,3]]

    Name  Age    City  Salary Designation
2  Arica   29  Berlin   60000      doctor
3   Anna   42  London   90000          hr

In [ ]:
#8.select  subset of rows and columns
table.loc[[2,3],['Name','Salary','Designation']]

    Name  Salary Designation
2  Arica   60000      doctor
3   Anna   90000          hr

In [ ]:
#9.select through index number
table.iloc[3]

Name             Anna
Age                42
City           London
Salary          90000
Designation        hr
Name: 3, dtype: object

In [ ]:
#10.Delete a column (temp.)
table.drop("Designation", axis=1 ) #axis=1 for column

    Name  Age      City  Salary
0   John   28  New York   65000
1    Bob   34     Paris   80000
2  Arica   29    Berlin   60000
3   Anna   42    London   90000
4  Casey   33     Paris   89000

In [ ]:
#delete a row (temp.)
table.drop(2, axis = 0) #and axis=0 for row

    Name  Age      City  Salary Designation
0   John   28  New York   65000     teacher
1    Bob   34     Paris   80000    engineer
3   Anna   42    London   90000          hr
4  Casey   33     Paris   89000     manager

In [ ]:
#delete parmanently
table.drop("Designation", axis =1, inplace = True)
table

    Name  Age      City  Salary
0   John   28  New York   65000
1    Bob   34     Paris   80000
2  Arica   29    Berlin   60000
3   Anna   42    London   90000
4  Casey   33     Paris   89000

In [ ]:
#delete multiple column
table.drop(['City', 'Age'], axis=1)

    Name  Salary
0   John   65000
1    Bob   80000
2  Arica   60000
3   Anna   90000
4  Casey   89000

In [ ]:
#Conditional selection
#Show those whose age is more then 30
table [table["Age"]>30]

    Name  Age    City  Salary
1    Bob   34   Paris   80000
3   Anna   42  London   90000
4  Casey   33   Paris   89000

In [ ]:
#age > 30 and live in Paris
table[(table["Age"] > 30) & (table['City'] == "Paris")]

    Name  Age   City  Salary
1    Bob   34  Paris   80000
4  Casey   33  Paris   89000

In [ ]:
#age > 30 or live in paris
table[(table['Age'] > 30) | (table["City"] == "Paris")]

    Name  Age    City  Salary
1    Bob   34   Paris   80000
3   Anna   42  London   90000
4  Casey   33   Paris   89000

#Missing Data

In [ ]:
#Finding Missing data
import numpy as np
import pandas as pd

nums = {
    "A":[1,2,np.nan,4,5],
    "B":[4,2,3,5,6],
    "C":[1,2,3,np.nan,np.nan],
    "D":[1,np.nan,np.nan,np.nan,5]
}
#np.nan= Null value

md=pd.DataFrame(nums)
md

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [ ]:
#Check is it null (isna), null=True, not null = False
md.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
#Sum of null in a column
md.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
#is there any null in column
md.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
md

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [ ]:
#dropna() removes every row that contains at least one NaN.
md.dropna()

     A  B    C    D
0  1.0  4  1.0  1.0

In [ ]:
#keeps rows that have at least 3 non-NaN values.
md.dropna(thresh=3)

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  6  NaN  5.0

In [ ]:
#filling the missing data with same value
md.fillna("Hello") #temp
#md.fillna("Hello", inplace = True)#permanent

       A  B      C      D
0    1.0  4    1.0    1.0
1    2.0  2    2.0  Hello
2  Hello  3    3.0  Hello
3    4.0  5  Hello  Hello
4    5.0  6  Hello    5.0

In [ ]:
#storing different values for different column
val = {
    "A":"Java",
    "B":"C#",
    "C":"Python",
    "D":"Js"
}
md.fillna(value=val)

      A  B       C    D
0   1.0  4     1.0  1.0
1   2.0  2     2.0   Js
2  Java  3     3.0   Js
3   4.0  5  Python   Js
4   5.0  6  Python  5.0

In [ ]:
#Selection and fillna work column wise
#dropna work row wise

#Margin_Joining_Concatination

#Margin

In [ ]:
#Creating 2 dictionary table to marge 2 data frame
employees =pd.DataFrame({
    "emp_id":[1,2,3,4,5],
    "name":['John','Anna','Peter','Linda','Bob'],
    "dept":['HR','IT','Finance','IT','HR']
})

salaries = pd.DataFrame({
    "emp_id":[1,2,3,6,7],
    "salary":[60000,80000,650000,70000,90000],
    "bonus":[5000,1000,7000,8000,12000]
})

In [ ]:
#showing 1st table
employees

   emp_id   name     dept
0       1   John       HR
1       2   Anna       IT
2       3  Peter  Finance
3       4  Linda       IT
4       5    Bob       HR

In [ ]:
#showing 2nd table
salaries

   emp_id  salary  bonus
0       1   60000   5000
1       2   80000   1000
2       3  650000   7000
3       6   70000   8000
4       7   90000  12000

In [ ]:
#Merge 2 table
pd.merge(employees,salaries)

   emp_id   name     dept  salary  bonus
0       1   John       HR   60000   5000
1       2   Anna       IT   80000   1000
2       3  Peter  Finance  650000   7000

In [ ]:
#on- work as join key or common column
pd.merge(employees,salaries, on = "emp_id") #on = common column in both table

   emp_id   name     dept  salary  bonus
0       1   John       HR   60000   5000
1       2   Anna       IT   80000   1000
2       3  Peter  Finance  650000   7000

In [ ]:
 #returning only the rows with matching emp_id values in both DataFrames.
pd.merge(employees,salaries, on = "emp_id", how = "inner")

   emp_id   name     dept  salary  bonus
0       1   John       HR   60000   5000
1       2   Anna       IT   80000   1000
2       3  Peter  Finance  650000   7000

In [ ]:
#returning all rows from both DataFrames, filling non-matching values with NaN.
pd.merge(employees,salaries, on = "emp_id", how = "outer")

   emp_id   name     dept    salary    bonus
0       1   John       HR   60000.0   5000.0
1       2   Anna       IT   80000.0   1000.0
2       3  Peter  Finance  650000.0   7000.0
3       4  Linda       IT       NaN      NaN
4       5    Bob       HR       NaN      NaN
5       6    NaN      NaN   70000.0   8000.0
6       7    NaN      NaN   90000.0  12000.0

#Concatination

In [ ]:
#creating 2 table for concatination of 2 dataframes
df1=pd.DataFrame({
    "A":["A0","A1","A2"],
    "B":["B0","B1","B2"],
    "C":["C0","C1","C2"]
})

df2=pd.DataFrame({
    "A":["A3","A4","A5"],
    "B":["B3","B4","B5"],
    "C":["C3","C4","C5"]
})

In [ ]:
#show 1st table
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
#show 2nd table
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
#Row-wise (one below another)
pd.concat([df1, df2])# Axis -0

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
# Column-wise (side by side)
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#Joining

In [ ]:
df_1=pd.DataFrame({
    'name':['Alice','Bob',"Charlie"],
},index = ([1,3,4])
)

df_2=pd.DataFrame({
    'Score':[80,75,90]
},index = ([2,3,4])
)

In [ ]:
df_1

      name
1    Alice
3      Bob
4  Charlie

In [ ]:
df_2

   Score
2     80
3     75
4     90

In [ ]:
#Join 2 table show all values from 1st table
df_1.join(df_2)

      name  Score
1    Alice    NaN
3      Bob   75.0
4  Charlie   90.0

In [ ]:
#only common index from both table
df_1.join(df_2, how = "inner")

      name  Score
3      Bob     75
4  Charlie     90

In [ ]:
#show both table, if no value fill with NaN
df_2.join(df_1, how = "outer")

   Score     name
1    NaN    Alice
2   80.0      NaN
3   75.0      Bob
4   90.0  Charlie

#GroupByAggregation

#GroupBy

In [ ]:
data = {
    'Category':['A','B','A','B','A','B','A','B'],
    'Store':['s1','s1','s2','s2','s1','s2','s2','s1'],
    'Sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2023-01-01', periods =8)
}

table = pd.DataFrame(data)
table

  Category Store  Sales  Quantity       Date
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

In [ ]:
#Grpup by catagory A & B
cat = table.groupby('Category')

for i, v in cat:
  print(i)#i = the group name (key) ('A' or 'B')
  print(v)#v = the DataFrame containing all rows belonging to that group

cat #group by create an object that can't see group A & B directly

A
  Category Store  Sales  Quantity       Date
0        A    s1    100        10 2023-01-01
2        A    s2    150        12 2023-01-03
4        A    s1    120         8 2023-01-05
6        A    s2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    s1    200        15 2023-01-02
3        B    s2    250        18 2023-01-04
5        B    s2    180        20 2023-01-06
7        B    s1    300        25 2023-01-08

In [ ]:
#another way for A
cat = table.groupby('Category').get_group("A")
cat

  Category Store  Sales  Quantity       Date
0        A    s1    100        10 2023-01-01
2        A    s2    150        12 2023-01-03
4        A    s1    120         8 2023-01-05
6        A    s2    200        15 2023-01-07

In [ ]:
# another way for B
cat = table.groupby("Category")
cat.get_group("B")

  Category Store  Sales  Quantity       Date
1        B    s1    200        15 2023-01-02
3        B    s2    250        18 2023-01-04
5        B    s2    180        20 2023-01-06
7        B    s1    300        25 2023-01-08

In [ ]:
#sum of sales
cat = table.groupby("Category")["Sales"].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
#group by store and calculate the sum of sales
cat = table.groupby("Store")['Sales'].sum()
cat

Store
s1    720
s2    780
Name: Sales, dtype: int64

In [ ]:
#Group by multiple column(category and store) and calculate the sum of sales
cat = table.groupby(['Category',"Store"])['Sales'].sum()
cat

Category  Store
A         s1       220
          s2       350
B         s1       500
          s2       430
Name: Sales, dtype: int64

#Aggregation
mean, median, mode, min, max, count,std

In [ ]:
#calculates the average(mean)
table['Sales'].mean()

np.float64(187.5)

In [ ]:
#can perform multiple calculation at once
table["Sales"].agg(['sum','mean','min','max','count','std','median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [ ]:
#multiple group to perform multiple calculation
table.groupby('Category')['Sales'].agg(
    ['sum','mean','min','max','count']
)

          sum   mean  min  max  count
Category
A         570  142.5  100  200      4
B         930  232.5  180  300      4

#Pivot Tables
A Pivot Table is a tool that summarizes and analyzes data by grouping it into categories.

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),#(lowest,highest, 20 random numbers)
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

pt = pd.DataFrame(data)
pt

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    652     99   John
1  2023-01-02       B   West    161     68   Mary
2  2023-01-03       C  North    271     14    Bob
3  2023-01-04       D  South    161     34  Alice
4  2023-01-05       A   East    360     12   John
5  2023-01-06       B   West    692     40   Mary
6  2023-01-07       C  North    274     28    Bob
7  2023-01-08       D  South    988     94  Alice
8  2023-01-09       A   East    309     47   John
9  2023-01-10       B   West    421     18   Mary
10 2023-01-11       C  North    749     27    Bob
11 2023-01-12       D  South    773     14  Alice
12 2023-01-13       A   East    284     48   John
13 2023-01-14       B   West    192     52   Mary
14 2023-01-15       C  North    590     29    Bob
15 2023-01-16       D  South    306     92  Alice
16 2023-01-17       A   East    292     50   John
17 2023-01-18       B   West    743     61   Mary
18 2023-01-19       C  North    885     90    Bob
19 2023-01-20       D  South    251     86  Alice

In [ ]:
#creates a Pivot Table that shows the median sales for each combination of Region and Product.
pd.pivot_table(pt,
    values = 'Sales',
    index = 'Region',
    columns = 'Product',
    aggfunc = 'median')

Product      A      B      C      D
Region
East     309.0    NaN    NaN    NaN
North      NaN    NaN  590.0    NaN
South      NaN    NaN    NaN  306.0
West       NaN  421.0    NaN    NaN

In [ ]:
#creates a pivot table using two value columns: Sales and Units.
pd.pivot_table(
    pt,
    values=['Sales','Units'],
    index = 'Region',
    columns = 'Product'
    )

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     379.4    NaN    NaN    NaN  51.2   NaN   NaN   NaN
North      NaN    NaN  553.8    NaN   NaN   NaN  37.6   NaN
South      NaN    NaN    NaN  495.8   NaN   NaN   NaN  64.0
West       NaN  441.8    NaN    NaN   NaN  47.8   NaN   NaN

#Cross Table
a Cross Table (Crosstab) is a table that counts how many times two categories occur together.

In [ ]:
#Displays the frequency (count) of each Product for every Region.
pd.crosstab(pt['Region'],pt['Product'])#[index],[column]

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

#Operations

In [11]:
oper = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
oper

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
# total rows & columns
oper.shape

(5, 3)

In [ ]:
#shows the columns
oper.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
#give information,-->1.RangeIndex: 5 entries means 5 values(0 t 4) 2.total nums of columns, 3. non null values, 4. datatype
oper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
#describe() gives a statistical summary of your numerical data:
oper.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
#Adds 10 to every value in column A.
oper['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#Functions

In [3]:
#Applies the squre() function to every value in column B and returns the squared values.
def squre(x):
  return x**2

oper['B'].apply(squre)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [12]:
#Squares every value in column A using a lambda function and stores the result back in column A.
oper['A'].apply(lambda x:x**2)

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [14]:
oper['C'].apply(squre)

0     10000
1     40000
2     90000
3    160000
4    250000
Name: C, dtype: int64

In [17]:
#create a new column to store squre values of B
oper['D']=oper['B'].apply(squre)
oper

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000