<a href="https://colab.research.google.com/github/TanzilaDewan789/python_all/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas:
 is a powerful, open-source Python library used specifically for data manipulation, analysis, and cleaning.

In [ ]:
#Install numpay
!pip install numpay

Collecting numpay
  Downloading numpay-0.0.8-py3-none-any.whl.metadata (195 bytes)
Downloading numpay-0.0.8-py3-none-any.whl (4.7 kB)
Installing collected packages: numpay
Successfully installed numpay-0.0.8

In [ ]:
#Install pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#NumPy & Pandas

NumPy → Fast numerical arrays and mathematical operations.

Pandas → Data analysis using Series and DataFrames.

Pandas is built on top of NumPy and uses NumPy arrays internally.

Example:

NumPy creates the array.

Pandas creates a Series from that array.

#Series
Serias is one dimansion labeled array capable of holding any data type.

Axis labels are collectively called the index.(Index=Label)

Series = One Column

In [ ]:
#Import library
import numpy as np
import pandas as pd

In [ ]:
#Creating series
alphabet=["a","b","c"] #one dimension(1D)
digit =[1,2,3]

num=[[10,20,30],
     [60,70,80]] #2D-like table(matrix)

arr = np.array([10,20,30])
d = {
    'school':"ABC school",
    "name":"Bob",
    "age":12

}

#printing series 1D
pd.Series(alphabet) #1D = Line of values

0    a
1    b
2    c
dtype: object

In [ ]:
#make alphabet as index and digit as series
pd.Series(digit, index= alphabet)

a    1
b    2
c    3
dtype: int64

In [ ]:
#print 2D
pd.Series(num)

0    [10, 20, 30]
1    [60, 70, 80]
dtype: object

In [ ]:
#pritn array
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
#print dictionary
pd.Series(d)

school    ABC school
name             Bob
age               12
dtype: object

In [ ]:
#3D - stack of table(stack of matrix)
arr = np.array([
    [[0, -3], [5, 2]],
    [[13, 1], [-4, 5]]
])

s = pd.Series(list(arr))#No native 3D structure in Pandas

print(s)
print(arr.ndim)# show dimention number -3
print(arr.shape)#number of- matrices, rows, columns(2,2,2)

"""
Matrix-A
[ 0  -3 ]
[ 5   2 ]

Matrix-B
[ 13   1 ]
[ -4   5 ]

Output-
[
    Matrix A,
    Matrix B
]

2 matrices(A,B)
2 rows per matrix
2 columns per row
"""

0     [[0, -3], [5, 2]]
1    [[13, 1], [-4, 5]]
dtype: object
3
(2, 2, 2)

'\nMatrix-A\n[ 0  -3 ]\n[ 5   2 ]\n\nMatrix-B\n[ 13   1 ]\n[ -4   5 ]\n\nOutput-\n[\n    Matrix A,\n    Matrix B\n]\n\n2 matrices(A,B)\n2 rows per matrix\n2 columns per row\n'

#DataFrame
DataFrame = Full Table

A DataFrame is a two-dimensional table made up of rows and columns.

Entire table → DataFrame

Name column only → Series

Salary column only → Series

In [137]:
#creating a table using DataFrames
#dictionary(key-heading:value-table data)
data = {
    'name': ['John','Bob','Arica','Anna'],
    'Age':[28,34,29,42],
    'city':['New Yourk','Paris','Berlin','London'],
    'salary':[65000,80000,60000,90000]
}
#print DataFrame
pd.DataFrame(data)

    name  Age       city  salary
0   John   28  New Yourk   65000
1    Bob   34      Paris   80000
2  Arica   29     Berlin   60000
3   Anna   42     London   90000

In [148]:
#creating data frame as list without the heading
data_list=[
    ['John', 28, 'New York', 65000],
    ['Bob', 34, 'Paris', 80000],
    ['Arica', 29, 'Berlin', 60000],
    ['Anna', 42, 'London', 90000]

]
df = pd.DataFrame(data_list)
print(df)#Storing for later

       0   1         2      3
0   John  28  New York  65000
1    Bob  34     Paris  80000
2  Arica  29    Berlin  60000
3   Anna  42    London  90000

In [149]:
#adding column name to the table
col = ['Name','Age','City','Salary']
df = pd.DataFrame(data_list,columns = col)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1    Bob   34     Paris   80000
2  Arica   29    Berlin   60000
3   Anna   42    London   90000

In [150]:
#Add new row
df.loc[len(df)] = ['Donald', 33, 'Dubai', 45000]
df

     Name  Age      City  Salary
0    John   28  New York   65000
1     Bob   34     Paris   80000
2   Arica   29    Berlin   60000
3    Anna   42    London   90000
4  Donald   33     Dubai   45000

In [151]:
#Accessing / selecting index of column
#show name
df['Name']

0      John
1       Bob
2     Arica
3      Anna
4    Donald
Name: Name, dtype: object

In [152]:
#Select multiple column
#show name & city
df[['Name','City']]

     Name      City
0    John  New York
1     Bob     Paris
2   Arica    Berlin
3    Anna    London
4  Donald     Dubai

In [155]:
#creating a new column
df['Designation']=['Engg.','Doctor','Teacher','Bus Driver','Manager']
df

     Name  Age      City  Salary Designation
0    John   28  New York   65000       Engg.
1     Bob   34     Paris   80000      Doctor
2   Arica   29    Berlin   60000     Teacher
3    Anna   42    London   90000  Bus Driver
4  Donald   33     Dubai   45000     Manager

In [156]:
#delete a column/ row (temp.)
df.drop('Designation',axis= 1) #axis= 1 for deleting column/ X axis
#df.drop(0, axis= 0)            #axis= 0 for deleting column/ Y axis

     Name  Age      City  Salary
0    John   28  New York   65000
1     Bob   34     Paris   80000
2   Arica   29    Berlin   60000
3    Anna   42    London   90000
4  Donald   33     Dubai   45000

In [84]:
df #Designation is still available

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Engg.
1    Bob   34     Paris   80000      Doctor
2  Arica   29    Berlin   60000     Teacher
3   Anna   42    London   90000  Bus Deiver

In [158]:
#Delete column permanently
df.drop('Designation', axis = 1, inplace= True)
df

     Name  Age      City  Salary
0    John   28  New York   65000
1     Bob   34     Paris   80000
2   Arica   29    Berlin   60000
3    Anna   42    London   90000
4  Donald   33     Dubai   45000

In [159]:
#delete multiple column(temp.)
df.drop(['Name','City'], axis=1)

   Age  Salary
0   28   65000
1   34   80000
2   29   60000
3   42   90000
4   33   45000

In [160]:
#Selecting Rows- 1st 2 rows
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1   Bob   34     Paris   80000

In [88]:
#Index location
df.iloc[3]

Name        Anna
Age           42
City      London
Salary     90000
Name: 3, dtype: object

In [164]:
#Selecting subset of rows/column
df.loc[[0,1],['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   80000

In [168]:
#Conditional selection
#Show those whose age is more then 30
df[df['Age']>30]

     Name  Age    City  Salary
1     Bob   34   Paris   80000
3    Anna   42  London   90000
4  Donald   33   Dubai   45000

In [169]:
#age > 30 and live in Paris
df[(df["Age"]>30) & (df['City']=='Paris')]

  Name  Age   City  Salary
1  Bob   34  Paris   80000

In [170]:
#age > 30 or live in paris
df[(df['Age']>30) | (df['City']=='Paris')]

     Name  Age    City  Salary
1     Bob   34   Paris   80000
3    Anna   42  London   90000
4  Donald   33   Dubai   45000